#ifndef GLOBALS_H
#define GLOBALS_H

#define M_PI 3.14159265f

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 576
#define WINDOW_POS_X 100
#define WINDOW_POS_Y 20
#define FRAME_DURATION 20

#define BALL_RADIUS 0.2f
#define BALL_INIT_POSITION_X 0.0f
#define BALL_INIT_POSITION_Z -2.0f
#define BALL_LINEAR_SPEED 5.0f
#define BALL_ANGULAR_SPEED 720.0f
#define MAX_BALL_THROWS 10

#define TARGET30_SIZE 0.6f
#define TARGET20_SIZE 0.8f
#define TARGET10_SIZE 1.0f

#define WALL_HEIGHT 3.0f
#define SIDE_WALL_LENGTH 8.0f
#define FRONT_WALL_LENGTH 8.0f

#define SLIDER_THICKNESS 30.0f
#define SLIDER_LENGTH 180.0f
#define SLIDER_POSITION_X 40.0f
#define SLIDER_POSITION_Y 150.0f
#define SLIDER_INCREMENT  0.05f

#define PALM_WIDTH 0.5f
#define PALM_HEIGHT 2.0f
#define FLOWER_WIDTH 0.6f
#define FLOWER_HEIGHT 0.6f

#define SKYBOX_SIZE 100.0f
#define SKYBOX_ROTATION_SPEED 3.0f

#endif // !GLOBALS_H
